version: "3.3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "labs"